version: '3.7'
# Define the services/containers to be run
services:
  frontend-service: # name of the first service
    image: fetest:0.0.1
    build: 
      context: ../FE-e-commerce/e-commerce
      dockerfile: Dockerfile 
    #volumes: # Volume binding
    #- './:/usr/src/app'
    ports:
      - "4200:4200"
    networks:
      - reg-network   
      
  naming-server:
    image: aviruptatai/namingserver:0.0.1
    build:
      context: EurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - reg-network
      
  gateway-service:
    image: aviruptatai/gatewayservice:0.0.1
    build:
      context: GatewayServer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - naming-server
    networks:
      - reg-network
  registration-service:
    image: aviruptatai/regservice:0.0.1
    build:
      context: registration-service
      dockerfile: Dockerfile    
    ports:
      - "8084:8083"
    restart: always
    depends_on:
      - naming-server
      - mysql
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: world
      RDS_USERNAME: root
      RDS_PASSWORD: Ar!ndam0112358
    networks:
      - reg-network
      
  cart-service:
    image: aviruptatai/cartservice:0.0.1
    build:
      context: cartservice
      dockerfile: Dockerfile    
    ports:
      - "8086:8084"
    restart: always
    depends_on:
      - naming-server
      - mysql
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: world
      RDS_USERNAME: root
      RDS_PASSWORD: Ar!ndam0112358
    networks:
      - reg-network
      
  product-service:
    image: aviruptatai/productservice:0.0.1
    build:
      context: productservice
      dockerfile: Dockerfile    
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - naming-server
      - mysql
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: world
      RDS_USERNAME: root
      RDS_PASSWORD: Ar!ndam0112358
    networks:
      - reg-network

  mysql:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Ar!ndam0112358 
      MYSQL_USER: root
      MYSQL_PASSWORD: Ar!ndam0112358
      MYSQL_DATABASE: world
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - reg-network
  
# Networks to be created to facilitate communication between containers
networks:
  reg-network:

volumes:
  mysql-database-data-volume: